### ISSUE TITLE
Any example of running this together with homebridge container?

### ISSUE THREAD

**Issue by nklint** [hedlund/rpi-telldus#1]
Hi!

I'm new to docker and haven't fully figured how to link this container to another docker container.
Since this container runs a daemon and not a network service, how do I expose the telldusd service to another container?

I want to run it together with the container oznu/homebridge

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:no-avahi-raspberry-pi
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ./volumes/homebridge:/homebridge
```

Would you mind explaining how the integration is supposed to work? the example you provided with "--volumes-from", how does this expose the daemon?

It would be great if you could provide an additional example.

Cheers!
Gustaf
